import ij.*;
import ij.process.*;
import ij.gui.*;
import java.awt.*;
import ij.plugin.*;
import ij.plugin.frame.*;

// import ij.text.TextWindow;
import java.security.SecureRandom;
import ij.io.SaveDialog;
import java.io.IOException;
import java.io.File;
import java.io.FileWriter;

/**
 * This plugin generate text file data has been written.
 * Data is a sequence of generated by only -1 or +1.
 * @author <a href="https://github.com/Y-Ichioka">Y-Ichioka</a>
 * @version 0.1
 * @see <a href="https://imagej.nih.gov/ij/developer/api/ij/plugin/PlugIn.html">PlugIn (ImageJ API)</a>
 */
public class Load_Sample_Data implements PlugIn {

  /**
   * This method is concrete method of PlugIn class.
   * It's executed at first.
   * @see <a href="https://imagej.nih.gov/ij/developer/api/ij/plugin/PlugIn.html">PlugIn (ImageJ API)</a>
   */
  @Override
  public void run(String arg) {
    // input
    GenericDialog gd = new GenericDialog("Set Option");

    String[] option = new String[3];
    option[0] = "random";
    option[1] = "all +1";
    option[2] = "all -1";

    gd.addStringField("title ", "sample data");
    gd.addChoice("style ", option, option[0]);
    gd.addNumericField("seed ", 1234, 0);
    gd.addNumericField("length ", 8, 0);

    gd.showDialog();
    if (gd.wasCanceled()) {
      return;
    }

    // get
    String title = gd.getNextString();
    String select = gd.getNextChoice();
    int seed = (int)gd.getNextNumber();
    int length = (int)gd.getNextNumber();

    // IJ.log(title);
    // IJ.log(select);
    // IJ.log("" + seed);
    // IJ.log("" + length);

    String out = "";

    if (select.equals(option[0])) {
      // random
      SecureRandom random = new SecureRandom();
      random.setSeed(seed);
      byte bytes[] = new byte[length];
      random.nextBytes(bytes);

      for (int i=0; i<length; i++) {
        if (bytes[i] % 2 == 0) {
          out += "+1\n";
        } else {
          out += "-1\n";
        }
      }
    } else if (select.equals(option[1])) {
      // all +1
      for (int i=0; i<length; i++) {
        out += "+1\n";
      }
    } else if (select.equals(option[2])) {
      // all -1
      for (int i=0; i<length; i++) {
        out += "-1\n";
      }
    } else {
      return;
    }

    // output
    // TextWindow tw = new TextWindow(title, out, 100, 300);

    SaveDialog saveDialog = new SaveDialog("Save", title, ".txt");

    try{
      File file = new File(saveDialog.getDirectory() + saveDialog.getFileName());
      FileWriter filewriter = new FileWriter(file);

      filewriter.write(out);
      filewriter.close();
    } catch (IOException e) {
      IJ.error("" + e);
      return;
    }

  }

}
